@include('layouts.partials.sidebar._sidebar-item', [
    'isActive' => request()->routeIs([
        'guru.sekolah.*',
        'guru.guru.*',
        'guru.siswa.*',
        'guru.tingkatan.*',
        'guru.jurusan.*',
        'guru.tapel.*',
        'guru.mapel.*',
        'guru.kkm.*',
        'guru.kelas.*',
        'guru.pembelajaran.*',
        'guru.ekstrakulikuler.*',
        'guru.silabus.*',
    ]),
    'hasArrow' => true,
    'icon' => 'database',
    'itemName' => 'Master Data',
    'route' => 'javascript:void(0)',
    'subItems' => [
        [
            'name' => 'School Profile',
            'route' => route('guru.sekolah.index'),
            'isActive' => request()->routeIs('guru.sekolah.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Academic Year',
            'route' => route('guru.tapel.index'),
            'isActive' => request()->routeIs('guru.tapel.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Students',
            'route' => route('guru.siswa.index'),
            'isActive' => request()->routeIs('guru.siswa.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Teachers',
            'route' => route('guru.guru.index'),
            'isActive' => request()->routeIs('guru.guru.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Level',
            'route' => route('guru.tingkatan.index'),
            'isActive' => request()->routeIs('guru.tingkatan.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Line',
            'route' => route('guru.jurusan.index'),
            'isActive' => request()->routeIs('guru.jurusan.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Subjects',
            'route' => route('guru.mapel.index'),
            'isActive' => request()->routeIs('guru.mapel.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Class & Homeroom',
            'route' => route('guru.kelas.index'),
            'isActive' => request()->routeIs('guru.kelas.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Learning Data',
            'route' => route('guru.pembelajaran.index'),
            'isActive' => request()->routeIs('guru.pembelajaran.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Extracurricular',
            'route' => route('guru.ekstrakulikuler.index'),
            'isActive' => request()->routeIs('guru.ekstrakulikuler.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Syllabus',
            'route' => route('curriculum.silabus.index'),
            'isActive' => request()->routeIs('curriculum.silabus.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'TimeTable',
            'route' => 'javascript:void(0)',
            'isActive' => request()->routeIs(['guru.jadwalpelajaran.*', 'guru.jadwalmengajar.*']),
            'childHasArrow' => true,
            'childSubItems' => [
                [
                    'name' => 'Timeslot',
                    'route' => route('guru.timeslot.index'),
                    'isActive' => request()->routeIs('guru.timeslot.*'),
                ],
                [
                    'name' => 'Timetable',
                    'route' => route('guru.jadwalpelajaran.index'),
                    'isActive' => request()->routeIs('guru.jadwalpelajaran.*'),
                ],
                [
                    'name' => 'Timetable Teacher',
                    'route' => route('guru.jadwalmengajar.index'),
                    'isActive' => request()->routeIs('guru.jadwalmengajar.*'),
                ],
            ],
        ],
    ],
])
