@include('layouts.partials.sidebar._sidebar-item', [
    'isActive' => request()->routeIs([
        'admin.sekolah.*',
        'admin.guru.*',
        'admin.siswa.*',
        'admin.tingkatan.*',
        'admin.jurusan.*',
        'admin.tapel.*',
        'admin.mapel.*',
        'admin.kkm.*',
        'admin.kelas.*',
        'admin.pembelajaran.*',
        'admin.ekstrakulikuler.*',
        'admin.silabus.*',
        'admin.jadwalmengajar.*',
        'admin.jadwalpelajaran.*',
        'admin.timeslot.*',
    ]),
    'hasArrow' => true,
    'icon' => 'database',
    'itemName' => 'Master Data',
    'route' => 'javascript:void(0)',
    'subItems' => [
        [
            'name' => 'School Profile',
            'route' => route('admin.sekolah.index'),
            'isActive' => request()->routeIs('admin.sekolah.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Academic Year',
            'route' => route('admin.tapel.index'),
            'isActive' => request()->routeIs('admin.tapel.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Students',
            'route' => route('admin.siswa.index'),
            'isActive' => request()->routeIs('admin.siswa.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Teachers',
            'route' => route('admin.guru.index'),
            'isActive' => request()->routeIs('admin.guru.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Level',
            'route' => route('admin.tingkatan.index'),
            'isActive' => request()->routeIs('admin.tingkatan.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Line',
            'route' => route('admin.jurusan.index'),
            'isActive' => request()->routeIs('admin.jurusan.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Subjects',
            'route' => route('admin.mapel.index'),
            'isActive' => request()->routeIs('admin.mapel.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Class & Homeroom',
            'route' => route('admin.kelas.index'),
            'isActive' => request()->routeIs('admin.kelas.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Learning Data',
            'route' => route('admin.pembelajaran.index'),
            'isActive' => request()->routeIs('admin.pembelajaran.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Extracurricular',
            'route' => route('admin.ekstrakulikuler.index'),
            'isActive' => request()->routeIs('admin.ekstrakulikuler.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Syllabus',
            'route' => route('admin.silabus.index'),
            'isActive' => request()->routeIs('admin.silabus.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'TimeTable',
            'route' => 'javascript:void(0)',
            'isActive' => request()->routeIs(['admin.jadwalpelajaran.*', 'admin.jadwalmengajar.*']),
            'childHasArrow' => true,
            'childSubItems' => [
                [
                    'name' => 'Timeslot',
                    'route' => route('admin.timeslot.index'),
                    'isActive' => request()->routeIs('admin.timeslot.*'),
                ],
                [
                    'name' => 'Timetable',
                    'route' => route('admin.jadwalpelajaran.index'),
                    'isActive' => request()->routeIs('admin.jadwalpelajaran.*'),
                ],
                [
                    'name' => 'Timetable Teacher',
                    'route' => route('admin.jadwalmengajar.index'),
                    'isActive' => request()->routeIs('admin.jadwalmengajar.*'),
                ],
            ],
        ],
    ],
])
