@include('layouts.partials.sidebar._sidebar-item', [
    'isActive' => request()->routeIs([
        'sekolah.*',
        'guru.*',
        'siswa.*',
        'tingkatan.*',
        'jurusan.*',
        'tapel.*',
        'mapel.*',
        'kkm.*',
        'kelas.*',
        'pembelajaran.*',
        'ekstrakulikuler.*',
        'admin.silabus.*',
    ]),
    'hasArrow' => true,
    'icon' => 'database',
    'itemName' => 'Master Data',
    'route' => 'javascript:void(0)',
    'subItems' => [
        [
            'name' => 'School Profile',
            'route' => route('sekolah.index'),
            'isActive' => request()->routeIs('sekolah.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Academic Year',
            'route' => route('tapel.index'),
            'isActive' => request()->routeIs('tapel.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Students',
            'route' => route('siswa.index'),
            'isActive' => request()->routeIs('siswa.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Teachers',
            'route' => route('guru.index'),
            'isActive' => request()->routeIs('guru.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Level',
            'route' => route('tingkatan.index'),
            'isActive' => request()->routeIs('tingkatan.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Line',
            'route' => route('jurusan.index'),
            'isActive' => request()->routeIs('jurusan.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Subjects',
            'route' => route('mapel.index'),
            'isActive' => request()->routeIs('mapel.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Class & Homeroom',
            'route' => route('kelas.index'),
            'isActive' => request()->routeIs('kelas.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Learning Data',
            'route' => route('pembelajaran.index'),
            'isActive' => request()->routeIs('pembelajaran.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Extracurricular',
            'route' => route('ekstrakulikuler.index'),
            'isActive' => request()->routeIs('ekstrakulikuler.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'Syllabus',
            'route' => route('admin.silabus.index'),
            'isActive' => request()->routeIs('admin.silabus.*'),
            'childHasArrow' => false,
        ],
        [
            'name' => 'TimeTable',
            'route' => 'javascript:void(0)',
            'isActive' => request()->routeIs('timeslot.*'),
            'childHasArrow' => true,
            'childSubItems' => [
                [
                    'name' => 'Timeslot',
                    'route' => route('jadwalpelajaran.timeslot.index'),
                    'isActive' => request()->routeIs('jadwalpelajaran.timeslot.*'),
                ],
                [
                    'name' => 'Timetable',
                    'route' => route('jadwalpelajaran.index'),
                    'isActive' => request()->routeIs('jadwalpelajaran.*'),
                ],
                [
                    'name' => 'Timetable Teacher',
                    'route' => route('jadwalmengajar.index'),
                    'isActive' => request()->routeIs('karyawan.*'),
                ],
            ],
        ],
    ],
])
